

#defaults are for SQIsign LVL1
FILENAME = "src/gf/ref/lvl1/fp_p5248_64.c"
Wordlength =64
Nlimbs =5
Radix =51
Nbits =251
Nbytes =32
COFACTOR = 5
TWO_POWER = 248
IDEAL_BITSIZE=256

#Input taking: Encoding size and filename with file generated by modarith
from sys import argv
IDEAL_BITSIZE = int(argv[1],10)
FILENAME = argv[2]

headlines = 3
read = open(FILENAME,"r")
rl = read.readlines()
read.close()
pstring = rl[3].split(" ")[1].strip()
p = int(pstring,16)
pp1 = p+1
print(hex(pp1))
TWO_POWER = 1
while(pp1%(2**TWO_POWER)==0):
    TWO_POWER = TWO_POWER+1
TWO_POWER = TWO_POWER-1
COFACTOR = pp1//(2**TWO_POWER)
Wordlength = int(rl[14].split(" ")[2].strip(),10)
Nlimbs = int(rl[15].split(" ")[2].strip(),10)
Radix = int(rl[16].split(" ")[2].strip(),10)
Nbits = int(rl[17].split(" ")[2].strip(),10)
Nbytes = int(rl[18].split(" ")[2].strip(),10)

print(COFACTOR,TWO_POWER,Wordlength,Nlimbs,Radix,Nbits,Nbytes)


WORDSIZE = Nlimbs
L_LEN = TWO_POWER
H_LEN = Wordlength-(L_LEN%64)
HGAP = ( WORDSIZE-1)* Wordlength-L_LEN-H_LEN
print(WORDSIZE*Wordlength,L_LEN,H_LEN)
HML_LEN = Wordlength-H_LEN
WSM2 = WORDSIZE-2
Nbytes8bits = Nbytes//8
if Nbytes8bits*8 < Nbytes:
    Nbytes8bits = Nbytes8bits+1
print("Nbytes ",Nbytes,"Nbytes8bits",Nbytes8bits, "WS-1==Nbytes8bits ",WORDSIZE-1==Nbytes8bits)
p = COFACTOR*2**TWO_POWER-1

#Code from ttps://stackoverflow.com/questions/4798654/modular-multiplicative-inverse-function-in-python
def egcd(a, b):
    if a == 0:
        return (b, 0, 1)
    else:
        g, y, x = egcd(b % a, a)
        return (g, x - (b // a) * y, y)

def modinv(a, m):
    g, x, y = egcd(a, m)
    if g != 1:
        raise Exception('modular inverse does not exist')
    else:
        return x % m
    
from math import ceil
print(Wordlength//4,2**(Wordlength-H_LEN)-1,2**(Wordlength-H_LEN)-1, (Wordlength-H_LEN), H_LEN, TWO_POWER,(WORDSIZE-1)*Wordlength)

# Reference for computing shift and inv5 https://ridiculousfish.com/blog/posts/labor-of-division-episode-i.html
shift = H_LEN+(COFACTOR).bit_length()
print(shift)
ffff = "0x"+"0"*(Wordlength//4-len(hex(2**(Wordlength-H_LEN)-1)[2:]))+(hex(2**(Wordlength-H_LEN)-1)[2:]).upper() #set Llen lower bits of a word
inv5 = "0x"+(hex(ceil((2**shift)/COFACTOR)))[2:].upper()

#Code from qt_Pegasis_C project's fp generation
def int_to_montgomery_fp_const(x):
    R = 2 ** (WORDSIZE * Radix)
    el = (x * R) % p
    vs = [(int(el) >> Radix * i) % 2**Radix for i in range(Nlimbs)]
    return "{" + ", ".join(map(hex, vs)) + "}"


cst0 = int_to_montgomery_fp_const(0)
cst1 = int_to_montgomery_fp_const(1)
cst2inv = int_to_montgomery_fp_const(modinv(2,p))
cst3inv = int_to_montgomery_fp_const(modinv(3,p))
cstR2 = int_to_montgomery_fp_const(2**IDEAL_BITSIZE)

init = """
// clang-format on
/******************************************************************************
 API functions calling generated code above
 ******************************************************************************/

#include <fp.h>\n
"""

constants = """const digit_t ZERO[NWORDS_FIELD] = {cst0};
const digit_t ONE[NWORDS_FIELD] = {cst1};
// Montgomery representation of 2^-1
static const digit_t TWO_INV[NWORDS_FIELD] = {cst2inv};
// Montgomery representation of 3^-1
static const digit_t THREE_INV[NWORDS_FIELD] = {cst3inv};
// Montgomery representation of 2^{IDEAL_BITSIZE}
static const digit_t R2[NWORDS_FIELD] = {cstR2};
\n\n""".format(cst0=cst0,cst1=cst1,cstR2=cstR2,cst2inv=cst2inv,cst3inv=cst3inv,IDEAL_BITSIZE=IDEAL_BITSIZE)

static = """void
fp_set_small(fp_t *x, const digit_t val)
{
    modint((int)val, *x);
}

void
fp_mul_small(fp_t *x, const fp_t *a, const uint32_t val)
{
    modmli(*a, (int)val, *x);
}

void
fp_set_zero(fp_t *x)
{
    modzer(*x);
}

void
fp_set_one(fp_t *x)
{
    modone(*x);
}

uint32_t
fp_is_equal(const fp_t *a, const fp_t *b)
{
    return -(uint32_t)modcmp(*a, *b);
}

uint32_t
fp_is_zero(const fp_t *a)
{
    return -(uint32_t)modis0(*a);
}

void
fp_copy(fp_t *out, const fp_t *a)
{
    modcpy(*a, *out);
}

void
fp_cswap(fp_t *a, fp_t *b, uint32_t ctl)
{
    modcsw((int)(ctl & 0x1), *a, *b);
}

void
fp_add(fp_t *out, const fp_t *a, const fp_t *b)
{
    modadd(*a, *b, *out);
}

void
fp_sub(fp_t *out, const fp_t *a, const fp_t *b)
{
    modsub(*a, *b, *out);
}

void
fp_neg(fp_t *out, const fp_t *a)
{
    modneg(*a, *out);
}

void
fp_sqr(fp_t *out, const fp_t *a)
{
    modsqr(*a, *out);
}

void
fp_mul(fp_t *out, const fp_t *a, const fp_t *b)
{
    modmul(*a, *b, *out);
}

void
fp_inv(fp_t *x)
{
    modinv(*x, NULL, *x);
}

uint32_t
fp_is_square(const fp_t *a)
{
    return -(uint32_t)modqr(NULL, *a);
}

void
fp_sqrt(fp_t *a)
{
    modsqrt(*a, NULL, *a);
}

void
fp_half(fp_t *out, const fp_t *a)
{
    modmul(TWO_INV, *a, *out);
}

void
fp_exp3div4(fp_t *out, const fp_t *a)
{
    modpro(*a, *out);
}

void
fp_div3(fp_t *out, const fp_t *a)
{
    modmul(THREE_INV, *a, *out);
}
"""

fe = """void
fp_encode(void *dst, const fp_t *a)
{{
    // Modified version of modexp()
    int i;
    spint c[{Nlimbs}];
    redc(*a, c);
    for (i = 0; i < {Nbytes}; i++) {{
        ((char *)dst)[i] = c[0] & (spint)0xff;
        (void)modshr(8, c);
    }}
}}
""".format(Nlimbs=Nlimbs,Nbytes=Nbytes)

fd = """uint32_t
fp_decode(fp_t *d, const void *src)
{{
    // Modified version of modimp()
    int i;
    spint res;
    const unsigned char *b = src;
    for (i = 0; i < {Nlimbs}; i++) {{
        (*d)[i] = 0;
    }}
    for (i = {Nbytes}; i >= 0; i--) {{
        modshl(8, *d);
        (*d)[0] += (spint)b[i];
    }}
    res = (spint)-modfsb(*d);
    nres(*d, *d);
    // If the value was canonical then res = -1; otherwise, res = 0
    for (i = 0; i < {Nlimbs}; i++) {{
        (*d)[i] &= res;
    }}
    return (uint32_t)res;
}}\n\n""".format(Nlimbs=Nlimbs,Nbytes=Nbytes-1)


f1 = """static inline unsigned char
add_carry(unsigned char cc, spint a, spint b, spint *d)
{
    udpint t = (udpint)a + (udpint)b + cc;
    *d = (spint)t;
    return (unsigned char)(t >> Wordlength);
}\n\n"""

f2 = """static void
partial_reduce(spint *out, const spint *src)
{{
    spint h, l, quo, rem;
    unsigned char cc;

    // Split value in high ({H_LEN} bits) and low ({L_LEN} bits) parts.
    h = src[{WSM2}] >> {HML_LEN};
    l = src[{WSM2}] & {ffff};

    // {COFACTOR}*2^{TWO_POWER} = 1 mod q; hence, we add floor(h/{COFACTOR}) + (h mod {COFACTOR})*2^{TWO_POWER}
    // to the low part.
    quo = (h * {inv5}) >> {shift};
    rem = h - ({COFACTOR} * quo);\n""".format(H_LEN=H_LEN,L_LEN=L_LEN,WSM2=WSM2-HGAP//Wordlength,HML_LEN=HML_LEN,COFACTOR=COFACTOR,TWO_POWER=TWO_POWER,ffff=ffff,shift=shift,inv5=inv5)


f2 = f2 +"    cc = add_carry(0, src[{i}], quo, &out[{i}]);\n".format(i=0)
for i in range(1,WSM2-HGAP//Wordlength):
    f2 = f2 +"    cc = add_carry(cc, src[{i}], 0, &out[{i}]);\n".format(i=i)

f2 = f2 + """    (void)add_carry(cc, l, rem << {HML_LEN}, &out[{WSM2}]);
}}\n\n""".format(HML_LEN=HML_LEN,WSM2=WSM2-HGAP//Wordlength)

f3 = """// Little-endian encoding of a 64-bit integer.
static inline void
enc64le(void *dst, uint64_t x)
{
    uint8_t *buf = dst;
    buf[0] = (uint8_t)x;
    buf[1] = (uint8_t)(x >> 8);
    buf[2] = (uint8_t)(x >> 16);
    buf[3] = (uint8_t)(x >> 24);
    buf[4] = (uint8_t)(x >> 32);
    buf[5] = (uint8_t)(x >> 40);
    buf[6] = (uint8_t)(x >> 48);
    buf[7] = (uint8_t)(x >> 56);
}\n\n"""

f4 = """// Little-endian decoding of a 64-bit integer.
static inline uint64_t
dec64le(const void *src)
{
    const uint8_t *buf = src;
    return (spint)buf[0] | ((spint)buf[1] << 8) | ((spint)buf[2] << 16) | ((spint)buf[3] << 24) |
           ((spint)buf[4] << 32) | ((spint)buf[5] << 40) | ((spint)buf[6] << 48) | ((spint)buf[7] << 56);
}\n\n"""

f5 = """void
fp_decode_reduce(fp_t *d, const void *src, size_t len)
{{
    uint64_t t[{Nbytes8bits}];   // Stores Nbytes * 8 bits
    uint8_t tmp[{Nbytes}]; // Nbytes
    const uint8_t *b = src;

    fp_set_zero(d);
    if (len == 0) {{
        return;
    }}

    size_t rem = len % {Nbytes};
    if (rem != 0) {{
        // Input size is not a multiple of {Nbytes}, we decode a partial
        // block, which is already less than 2^{TWO_POWER}.
        size_t k = len - rem;
        memcpy(tmp, b + k, len - k);
        memset(tmp + len - k, 0, (sizeof tmp) - (len - k));
        fp_decode(d, tmp);
        len = k;
    }}
    // Process all remaining blocks, in descending address order.
    while (len > 0) {{
        fp_mul(d, d, &R2);
        len -= {Nbytes};\n""".format(Nbytes=Nbytes8bits*8,Nbytes8bits=Nbytes8bits,TWO_POWER=TWO_POWER)
for i in range(Nbytes8bits):
    i8 = 8*i
    f5 = f5 +"        t[{i}] = dec64le(b + len + {i8});\n".format(i=i,i8=i8)
f5 = f5 +"        partial_reduce(t, t);\n"
for i in range(Nbytes8bits):
    i8 = 8*i
    f5 = f5 +"        enc64le(tmp + {i8}, t[{i}]);\n".format(i=i,i8=i8)
f5 = f5 + """        fp_t a;
        fp_decode(&a, tmp);
        fp_add(d, d, &a);
    }}
}}\n\n
""".format()

if __name__=="__main__":
    f =  open(FILENAME, "a")
    f.write(init+constants+static+fe+fd+f1+f2+f3+f4+f5)
