set(SOURCE_FILES_NIKE_GENERIC_REF
    ${LVLX_DIR}/nike_tools.c
    ${LVLX_DIR}/nike.c
)

add_library(${LIB_NIKE_${SVARIANT_UPPER}} STATIC ${SOURCE_FILES_NIKE_GENERIC_REF})
target_link_libraries(${LIB_NIKE_${SVARIANT_UPPER}} ${LIB_QUATERNION} ${LIB_PRECOMP_${SVARIANT_UPPER}} ${LIB_GF_${SVARIANT_UPPER}} ${LIB_EC_${SVARIANT_UPPER}} ${LIB_HD_${SVARIANT_UPPER}} ${LIB_VERIFICATION_${SVARIANT_UPPER}})
target_include_directories(${LIB_NIKE_${SVARIANT_UPPER}} PRIVATE ${INC_PUBLIC} ${INC_COMMON} ${INC_QUATERNION} ${INC_PRECOMP_${SVARIANT_UPPER}} ${INC_GF} ${INC_GF_${SVARIANT_UPPER}} ${INC_EC} ${INC_HD} ${INC_VERIFICATION} ${INC_NIKE})
target_compile_options(${LIB_NIKE_${SVARIANT_UPPER}} PRIVATE ${C_OPT_FLAGS})
target_compile_definitions(${LIB_NIKE_${SVARIANT_UPPER}} PUBLIC SQISIGN_VARIANT=${SVARIANT_LOWER})

add_subdirectory(test)
